language: cpp
dist: focal
os:
  - linux
compiler:
  - gcc
  - clang
env:
  - RUN_TEST=all
  - RUN_TEST=mra CMAKE_EXTRA_OPTIONS="-D ENABLE_GENTENSOR=1"
branches:
  only:
    - master
# MRA testsuite segfaults a la https://travis-ci.org/github/m-a-d-n-e-s-s/madness/jobs/665937224#L10269 ... can't reproduce, giving up
#  - RUN_TEST=all BUILD_SHARED=1
jobs:
  exclude:
    - os: linux
      compiler: clang
      env: RUN_TEST=mra CMAKE_EXTRA_OPTIONS="-D ENABLE_GENTENSOR=1"
addons:
  apt:
    update: true
    packages:
      - gcc-8
      - g++-8
      - gfortran-8
      - libblas-dev
      - liblapack-dev
# if necessary to debug the install step, move all lines into
# script step and add appropriate debugging analysis to the
# after_failure step e.g. find . -name config.log -exec cat {} ";"
install:
  - ./ci/dep-$TRAVIS_OS_NAME.sh
script:
  - ./ci/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./build/config.log
  - cat ./build/CMakeFiles/CMakeError.log
  - cat ./build/CMakeFiles/CMakeOutput.log
cache:
  ccache: true
  directories:
    - $HOME/mpich
    - $HOME/libxc
    - $HOME/ccache
    - /opt/intel
